### PR TITLE
🆕(site) Add reusable shape worklet

### LINKED ISSUE #319: Flexible Shapes Component
A flexible component is needed to handle the variety of shapes used throughout the homepage redesign. This component would ideally allow for masks, textures, colors, and potentially transforming or scaling.

I've prototyped using multiple options (existing circles worklet, pseudo elements, color stops, SVGs, etc), but each option has limitations or concerns such as overhead or a lack of reusability. 

Designs: https://www.figma.com/file/o9JHnISo2QrwyiKvLyRGys/Chrome-OS-Redesign-%5BFINAL%5D?node-id=2%3A4430

Modules that will use flexible shapes:
- Interstitial Banner (#212)
- Routing Cards (#209)
- Fifty Fifty (#262)

### PR DESCRIPTION
**Pull request by Snugug**
**Please describe what your Pull Request does**

Adds a paint worklet to draw the shapes we're looking to include for the redesign, and a style guide page explaining how to use them (including layering)

**Please tag each issue this Pull Request resolves**

- Resolves #319

### CODE REVIEW

**Comment by Vanss472** [comment]
Hey @Snugug, this is some pretty cool stuff. What do you think about potentially adding the patterns (arrows, brackets, double lines) to the shape?

Also, I noticed the circle and the moon aren't rendering in Safari or Firefox.
image

**Comment by Vanss472** [comment]
Hey @Snugug, this is some pretty cool stuff. What do you think about potentially adding the patterns (arrows, brackets, double lines) to the shape?

Also, I noticed the circle and the moon aren't rendering in Safari or Firefox.
image

**Comment by Snugug** [comment]
I had thought about adding the patterns, too, but decided against it for this PR so using these shapes can be unblocked for the rest of the work. We can't directly draw text in a Paint worklet so creating repeating patterns is a bigger haul for this ATM and in the meantime a repeating SVG can be used as a background image and these shapes can be used as the image component of a [`mask`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask)

**Comment by Snugug** [comment]
Also, it _appears_ to be working in Safari and Firefox for me? This image shows the style guide page in Chrome (left), Safari (middle), and Firefox (right) for me, with more or less the same thing being drawn in all of them. Safari is a little bit off, and both take a while to load in, but they all appear to be there.

Style Guide of the three shapes

**Review by Vanss472 — APPROVED** [review]

**Pull request merged**
