### PR TITLE
Ensure GitHub link points to right organization

### PR DESCRIPTION
**Pull request by leopic**
**Please describe what your Pull Request does**
Fixes an incorrect link and spelling for the link back to GitHub

**Please tag each issue this Pull Request resolves**

- Resolves #

### CODE REVIEW

**Comment by leopic** [comment]
@googlebot I signed it!

**Comment by nohe427** [comment]
Hi @leopic - Good catch!  Would you also be able to update the [URL located here](https://raw.githubusercontent.com/chromeos/chromeos.dev/trunk/pages/es/_data/community.yml) for our GitHub link so when we merge these changes in, the pages are consistent between the spanish and english versions of the site?

**Comment by leopic** [comment]
Hey @nohe427, good catch, I missed that.

Should be good to go now.

**Comment by nohe427** [comment]
Many thanks!
LGTM!

**Pull request merged**
